#!/usr/bin/env python
# GWA Calculator GUI

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GWA Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gwa_calculator(object):
    def __init__(self):
        self.research_grade = "1.00"
        self.core_grade = "1.00"
        self.elective_grade = "1.00"
        self.math_grade = "1.00"
        self.english_grade = "1.00"
        self.filipino_grade = "1.00"
        self.ss_grade = "1.00"

    def setupUi(self, gwa_calculator):
        gwa_calculator.setObjectName("gwa_calculator")
        gwa_calculator.resize(829, 561)
        self.centralwidget = QtWidgets.QWidget(gwa_calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.gwa = QtWidgets.QLabel(self.centralwidget)
        self.gwa.setGeometry(QtCore.QRect(4, 5, 821, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gwa.setFont(font)
        self.gwa.setMouseTracking(False)
        self.gwa.setAlignment(QtCore.Qt.AlignCenter)
        self.gwa.setObjectName("gwa")
        self.subject_research_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_research_label.setGeometry(QtCore.QRect(140, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_research_label.setFont(font)
        self.subject_research_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_research_label.setObjectName("subject_research_label")
        self.research_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.research_add_grade_button.setGeometry(QtCore.QRect(290, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.research_add_grade_button.setFont(font)
        self.research_add_grade_button.setCheckable(False)
        self.research_add_grade_button.setDefault(False)
        self.research_add_grade_button.setFlat(False)
        self.research_add_grade_button.setObjectName("research_add_grade_button")
        self.research_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.research_minus_grade_button.setGeometry(QtCore.QRect(40, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.research_minus_grade_button.setFont(font)
        self.research_minus_grade_button.setObjectName("research_minus_grade_button")
        self.core_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.core_add_grade_button.setGeometry(QtCore.QRect(290, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.core_add_grade_button.setFont(font)
        self.core_add_grade_button.setCheckable(False)
        self.core_add_grade_button.setDefault(False)
        self.core_add_grade_button.setFlat(False)
        self.core_add_grade_button.setObjectName("core_add_grade_button")
        self.core_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.core_minus_grade_button.setGeometry(QtCore.QRect(40, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.core_minus_grade_button.setFont(font)
        self.core_minus_grade_button.setObjectName("core_minus_grade_button")
        self.subject_core_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_core_label.setGeometry(QtCore.QRect(140, 180, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_core_label.setFont(font)
        self.subject_core_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_core_label.setObjectName("subject_core_label")
        self.elective_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.elective_add_grade_button.setGeometry(QtCore.QRect(290, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.elective_add_grade_button.setFont(font)
        self.elective_add_grade_button.setCheckable(False)
        self.elective_add_grade_button.setDefault(False)
        self.elective_add_grade_button.setFlat(False)
        self.elective_add_grade_button.setObjectName("elective_add_grade_button")
        self.elective_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.elective_minus_grade_button.setGeometry(QtCore.QRect(40, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.elective_minus_grade_button.setFont(font)
        self.elective_minus_grade_button.setObjectName("elective_minus_grade_button")
        self.subject_elective_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_elective_label.setGeometry(QtCore.QRect(140, 290, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_elective_label.setFont(font)
        self.subject_elective_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_elective_label.setObjectName("subject_elective_label")
        self.math_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.math_add_grade_button.setGeometry(QtCore.QRect(290, 430, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.math_add_grade_button.setFont(font)
        self.math_add_grade_button.setCheckable(False)
        self.math_add_grade_button.setDefault(False)
        self.math_add_grade_button.setFlat(False)
        self.math_add_grade_button.setObjectName("math_add_grade_button")
        self.math_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.math_minus_grade_button.setGeometry(QtCore.QRect(40, 430, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.math_minus_grade_button.setFont(font)
        self.math_minus_grade_button.setObjectName("math_minus_grade_button")
        self.subject_math_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_math_label.setGeometry(QtCore.QRect(140, 380, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_math_label.setFont(font)
        self.subject_math_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_math_label.setObjectName("subject_math_label")
        self.english_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.english_add_grade_button.setGeometry(QtCore.QRect(690, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.english_add_grade_button.setFont(font)
        self.english_add_grade_button.setCheckable(False)
        self.english_add_grade_button.setDefault(False)
        self.english_add_grade_button.setFlat(False)
        self.english_add_grade_button.setObjectName("english_add_grade_button")
        self.english_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.english_minus_grade_button.setGeometry(QtCore.QRect(440, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.english_minus_grade_button.setFont(font)
        self.english_minus_grade_button.setObjectName("english_minus_grade_button")
        self.subject_english_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_english_label.setGeometry(QtCore.QRect(540, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_english_label.setFont(font)
        self.subject_english_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_english_label.setObjectName("subject_english_label")
        self.filipino_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.filipino_add_grade_button.setGeometry(QtCore.QRect(690, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.filipino_add_grade_button.setFont(font)
        self.filipino_add_grade_button.setCheckable(False)
        self.filipino_add_grade_button.setDefault(False)
        self.filipino_add_grade_button.setFlat(False)
        self.filipino_add_grade_button.setObjectName("filipino_add_grade_button")
        self.filipino_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.filipino_minus_grade_button.setGeometry(QtCore.QRect(440, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.filipino_minus_grade_button.setFont(font)
        self.filipino_minus_grade_button.setObjectName("filipino_minus_grade_button")
        self.subject_filipino_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_filipino_label.setGeometry(QtCore.QRect(540, 180, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_filipino_label.setFont(font)
        self.subject_filipino_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_filipino_label.setObjectName("subject_filipino_label")
        self.ss_add_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.ss_add_grade_button.setGeometry(QtCore.QRect(690, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ss_add_grade_button.setFont(font)
        self.ss_add_grade_button.setCheckable(False)
        self.ss_add_grade_button.setDefault(False)
        self.ss_add_grade_button.setFlat(False)
        self.ss_add_grade_button.setObjectName("ss_add_grade_button")
        self.ss_minus_grade_button = QtWidgets.QPushButton(self.centralwidget)
        self.ss_minus_grade_button.setGeometry(QtCore.QRect(440, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ss_minus_grade_button.setFont(font)
        self.ss_minus_grade_button.setObjectName("ss_minus_grade_button")
        self.subject_ss_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_ss_label.setGeometry(QtCore.QRect(540, 290, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_ss_label.setFont(font)
        self.subject_ss_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_ss_label.setObjectName("subject_ss_label")
        self.elective_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.elective_grade_label.setGeometry(QtCore.QRect(140, 330, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.elective_grade_label.setFont(font)
        self.elective_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elective_grade_label.setObjectName("elective_grade_label")
        self.english_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.english_grade_label.setGeometry(QtCore.QRect(540, 120, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.english_grade_label.setFont(font)
        self.english_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.english_grade_label.setObjectName("english_grade_label")
        self.core_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.core_grade_label.setGeometry(QtCore.QRect(140, 230, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.core_grade_label.setFont(font)
        self.core_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.core_grade_label.setObjectName("core_grade_label")
        self.filipino_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.filipino_grade_label.setGeometry(QtCore.QRect(540, 230, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filipino_grade_label.setFont(font)
        self.filipino_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filipino_grade_label.setObjectName("filipino_grade_label")
        self.research_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.research_grade_label.setGeometry(QtCore.QRect(140, 120, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.research_grade_label.setFont(font)
        self.research_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.research_grade_label.setObjectName("research_grade_label")
        self.ss_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.ss_grade_label.setGeometry(QtCore.QRect(540, 330, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ss_grade_label.setFont(font)
        self.ss_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ss_grade_label.setObjectName("ss_grade_label")
        self.math_grade_label = QtWidgets.QLabel(self.centralwidget)
        self.math_grade_label.setGeometry(QtCore.QRect(140, 430, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.math_grade_label.setFont(font)
        self.math_grade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.math_grade_label.setObjectName("math_grade_label")
        gwa_calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gwa_calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        gwa_calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gwa_calculator)
        self.statusbar.setObjectName("statusbar")
        gwa_calculator.setStatusBar(self.statusbar)

        self.retranslateUi(gwa_calculator)
        QtCore.QMetaObject.connectSlotsByName(gwa_calculator)

    def calculate_final_gwa(self):
        research = float(self.research_grade) * 2.00
        core = float(self.core_grade) * 1.7
        elective = float(self.elective_grade) * 1.7
        math = float(self.math_grade)
        english = float(self.english_grade)
        filipino = float(self.filipino_grade)
        ss = float(self.ss_grade)

        return str(round((research + core + elective + math + english + filipino + ss)/9.4, 3))

    def research_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.research_grade) < 5.00:
            self.research_grade = str(float(self.research_grade) + 0.25)
            self.research_grade_label.setText(_translate("gwa_calculator", self.research_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def research_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.research_grade) > 1.00:
            self.research_grade = str(float(self.research_grade) - 0.25)
            self.research_grade_label.setText(_translate("gwa_calculator", self.research_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def core_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.core_grade) < 5.00:
            self.core_grade = str(float(self.core_grade) + 0.25)
            self.core_grade_label.setText(_translate("gwa_calculator", self.core_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def core_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.core_grade) > 1.00:
            self.core_grade = str(float(self.core_grade) - 0.25)
            self.core_grade_label.setText(_translate("gwa_calculator", self.core_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def elective_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.elective_grade) < 5.00:
            self.elective_grade = str(float(self.elective_grade) + 0.25)
            self.elective_grade_label.setText(_translate("gwa_calculator", self.elective_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def elective_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.elective_grade) > 1.00:
            self.elective_grade = str(float(self.elective_grade) - 0.25)
            self.elective_grade_label.setText(_translate("gwa_calculator", self.elective_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def math_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.math_grade) < 5.00:
            self.math_grade = str(float(self.math_grade) + 0.25)
            self.math_grade_label.setText(_translate("gwa_calculator", self.math_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def math_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.math_grade) > 1.00:
            self.math_grade = str(float(self.math_grade) - 0.25)
            self.math_grade_label.setText(_translate("gwa_calculator", self.math_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def english_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.english_grade) < 5.00:
            self.english_grade = str(float(self.english_grade) + 0.25)
            self.english_grade_label.setText(_translate("gwa_calculator", self.english_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def english_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.english_grade) > 1.00:
            self.english_grade = str(float(self.english_grade) - 0.25)
            self.english_grade_label.setText(_translate("gwa_calculator", self.english_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def filipino_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.filipino_grade) < 5.00:
            self.filipino_grade = str(float(self.filipino_grade) + 0.25)
            self.filipino_grade_label.setText(_translate("gwa_calculator", self.filipino_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def filipino_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.filipino_grade) > 1.00:
            self.filipino_grade = str(float(self.filipino_grade) - 0.25)
            self.filipino_grade_label.setText(_translate("gwa_calculator", self.filipino_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def ss_add_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.ss_grade) < 5.00:
            self.ss_grade = str(float(self.ss_grade) + 0.25)
            self.ss_grade_label.setText(_translate("gwa_calculator", self.ss_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def ss_minus_grade(self):
        _translate = QtCore.QCoreApplication.translate
        if float(self.ss_grade) > 1.00:
            self.ss_grade = str(float(self.ss_grade) - 0.25)
            self.ss_grade_label.setText(_translate("gwa_calculator", self.ss_grade))
            final_gwa = self.calculate_final_gwa()
            self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

    def retranslateUi(self, gwa_calculator):
        final_gwa = self.calculate_final_gwa()
        _translate = QtCore.QCoreApplication.translate
        gwa_calculator.setWindowTitle(_translate("gwa_calculator", "GWA Calculator"))
        self.gwa.setText(_translate("gwa_calculator", "GWA: " + final_gwa))

        self.subject_research_label.setText(_translate("gwa_calculator", "Research"))
        self.research_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.research_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.research_grade_label.setText(_translate("gwa_calculator", self.research_grade))
        self.research_add_grade_button.clicked.connect(self.research_add_grade)
        self.research_minus_grade_button.clicked.connect(self.research_minus_grade)

        self.core_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.core_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_core_label.setText(_translate("gwa_calculator", "Core"))
        self.core_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.core_add_grade_button.clicked.connect(self.core_add_grade)
        self.core_minus_grade_button.clicked.connect(self.core_minus_grade)

        self.elective_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.elective_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_elective_label.setText(_translate("gwa_calculator", "Elective"))
        self.elective_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.elective_add_grade_button.clicked.connect(self.elective_add_grade)
        self.elective_minus_grade_button.clicked.connect(self.elective_minus_grade)

        self.math_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.math_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_math_label.setText(_translate("gwa_calculator", "Math"))
        self.math_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.math_add_grade_button.clicked.connect(self.math_add_grade)
        self.math_minus_grade_button.clicked.connect(self.math_minus_grade)

        self.english_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.english_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_english_label.setText(_translate("gwa_calculator", "English"))
        self.english_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.english_add_grade_button.clicked.connect(self.english_add_grade)
        self.english_minus_grade_button.clicked.connect(self.english_minus_grade)

        self.filipino_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.filipino_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_filipino_label.setText(_translate("gwa_calculator", "Filipino"))
        self.filipino_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.filipino_add_grade_button.clicked.connect(self.filipino_add_grade)
        self.filipino_minus_grade_button.clicked.connect(self.filipino_minus_grade)

        self.ss_add_grade_button.setText(_translate("gwa_calculator", "+"))
        self.ss_minus_grade_button.setText(_translate("gwa_calculator", "-"))
        self.subject_ss_label.setText(_translate("gwa_calculator", "SS"))
        self.ss_grade_label.setText(_translate("gwa_calculator", "1.00"))
        self.ss_add_grade_button.clicked.connect(self.ss_add_grade)
        self.ss_minus_grade_button.clicked.connect(self.ss_minus_grade)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    gwa_calculator = QtWidgets.QMainWindow()
    ui = Ui_gwa_calculator()
    ui.setupUi(gwa_calculator)
    gwa_calculator.show()
    sys.exit(app.exec_())
